spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:h2:file:~/.h2/consume
    driver-class-name: org.h2.Driver
eureka:
  client:
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/